name: KatzcraftManagement
version: '0.3'
main: de.castmax1311.katzcraftmanagement.Main
api-version: '1.16'
description: A plugin to help admins manage their server
softdepend: [PlaceholderAPI] # This is used, if your plugin works without PlaceholderAPI.
commands:
    maintenance:
      description: Put your server in maintenance
      usage: /maintenance
    fly:
      description: Flight mode
      usage: /fly
