name: KatzcraftManagement
version: '1.3.1'
main: de.castmax1311.katzcraftmanagement.Main
api-version: '1.16'
description: A plugin to help admins manage their server
softdepend: [PlaceholderAPI] # This is used, if your plugin works without PlaceholderAPI.
commands:
    maintenance:
      description: Put your server in maintenance
      usage: /maintenance
    fly:
      description: Flight mode
      usage: /fly
    mute:
      description: Mute a player for a user-defined period of time
      usage: /mute <player> <time in seconds>
    vanish:
      description: Be invisible for all players
      usage: /vanish
    inventory:
      description: Look into the inventory of other players
      usage: /inventory <player>
    namecolor:
      description: Change the color of your name
      usage: /chatcolor <color>
    messagecolor:
      description: Change the color of your chat messages
      usage: /messagecolor <color>
    nickname:
      description: "/nickname <name> or for OP's: /nickname <player> <name>"
      usage: /nickname <player> <name>
    speed:
      description: Change your speed in walking or flying
      usage: /speed <fly / walk> <speed>
    motd:
      description: View the server description
      usage: /motd
    craft:
      description: Open the Crafting Table
      usage: /craft
    repair:
      description: Repair the item you're holding in your hand
      usage: /repair
    head:
      description: Give you heads from players
      usage: /head <player> <amount>
    heal:
      description: Fill up your hearts and hunger bars
      usage: /heal
    godmode:
      description: Become Immortal
      usage: /godmode
    freeze:
      description: Freeze players
      usage: /freeze <player>
