name: KatzcraftManagement
version: '0.2'
main: de.castmax1311.katzcraftmanagement.Main
api-version: '1.16'
description: A plugin to help admins manage your server
softdepend: [PlaceholderAPI] # This is used, if your plugin works without PlaceholderAPI.
commands:
    maintenance:
      usage:
